services:
  db:
    image: postgis/postgis:16-3.4-alpine  # Uses optimized Alpine Linux with Postgres 16 and PostGIS 3.4
    container_name: wazigov_spatial_db
    restart: always
    ports:
      - "5433:5432"  # Maps container port 5432 to your host port 5433 (changed from 5432 because port was in use)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Govan@2003  # Choose a strong password
      POSTGRES_DB: wazigov_db                  # Automatically builds your backend database on initialization
    volumes:
      - "./data/postgres_data:/var/lib/postgresql/data" # Persists your spatial data locally on your machine

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: wazigov_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Connect string: user postgres, pass Govan@2003, host db, port 5432, db wazigov_db
      DATABASE_URL: "postgresql://postgres:Govan%402003@db:5432/wazigov_db"
    depends_on:
      - db

volumes:
  pg_spatial_data:  # Named volume ensuring data isn't wiped when containers stop